name: "Helm Chart Releaser"
description: "Helm Chart Releaser that includes signing producing .asc file"
inputs:
  gpg_keyring_base64:
    description: "GPG Keyring in Base64"
    required: true
  gpg_passphrase:
    description: "GPG pass phrase"
    required: true
  gpg_key:
    description: "GPG Key Name"
    required: true
  gh_token:
    description: "GitHub Token that has access to create releases"
    required: true
  chart:
    description: "Directory for the Chart"
    required: true
  chart_version:
    description: "Version of the Chart"
    required: false
    default: ""
  image_repository:
    description: "Image Repo"
    required: false
    default: ""
  image_tag:
    description: "Image tag"
    required: false
    default: ""
  image_digest:
    description: "Image Digest"
    required: false
    default: ""
  notes:
    description: "Release Notes"
    required: false
    default: "Supply Chain Evidence Catalog"
runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
      with:
        version: "3.11.1"

    - name: Update Values and Chart
      if: "${{ inputs.chart_version != '' }}"
      id: chart
      uses: fjogeleit/yaml-update-action@d98ee6a10a971effea75480e3f315e4dacc89a23 # main
      with:
        commitChange: false
        changes: |
          {
            "chart/${{ github.event.repository.name }}/values.yaml":
            {
              "image.repository": "${{ inputs.image_repository }}",
              "image.tag": "${{ inputs.image_tag }}",
              "image.sha": "${{ inputs.image_digest }}"
            },
            "chart/${{ github.event.repository.name }}/Chart.yaml":
            {
              "version": "${{ inputs.chart_version }}",
              "appVersion": "${{ inputs.chart_version }}"
            }
          }

    - name: Use Node.js
      if: "${{ inputs.chart_version == '' }}"
      id: node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: "18.x"

    - name: Update Main Chart
      if: "${{ inputs.chart_version == '' }}"
      id: main_chart
      run: |
        sleep 5m
        yarn install
        node main.js
      shell: bash

    - name: Run chart-releaser
      run: |
        set -x
        gh_token="${{ inputs.gh_token }}"
        gpg_keyring_base64="${{ inputs.gpg_keyring_base64 }}"
        gpg_passphrase="${{ inputs.gpg_passphrase }}"
        gpg_keyring="/tmp/secring.gpg"
        gpg_passphrase_file="/tmp/passphrase"

        # Create keyring and passphrase file
        base64 -d <<< "${gpg_keyring_base64}" > "${gpg_keyring}"
        echo "${gpg_passphrase}" > "${gpg_passphrase_file}"

        # Add changed Chart and values
        git add ${{ inputs.chart }}/Chart.yaml
        if test -f "${{ inputs.chart }}/values.yaml"; then
          git add ${{ inputs.chart }}/values.yaml
        fi
        git commit -m "Updated chart and values"
        git push
        git status

        # Pull all the branches
        git pull --all; for remote in `git branch -r | grep -v main | grep -v \>`; do git branch --track ${remote#origin/} $remote; done

        # Loop until all of the dependencies are downloaded
        helm dep update "${{ inputs.chart }}"
        while [ $? -ne 0 ]
        do
          sleep 1m
          helm dep update "${{ inputs.chart }}"
        done

        # Helm Package with signing
        tag=$(basename $(helm package "${{ inputs.chart }}" -u --key "${{ inputs.gpg_key }}" --sign --keyring "${gpg_keyring}" --passphrase-file "${gpg_passphrase_file}" | cut -d: -f2) .tgz)
        echo "Created ${tag}"

        # Clean up GPG and intermediate tgz files
        rm -rf "${gpg_keyring}" "${gpg_passphrase_file}" ${{ inputs.chart }}/charts/*.tgz

        # Rename the signing .prov to .asc for OpenSSF Scorecard
        ls *.prov | xargs -I {} sh -c 'mv $1 `basename $1 .prov`.asc' - {}

        # Remove existing tags and releases
        gh release delete "${tag}" --cleanup-tag -y || true

        # Create new commit and release
        git tag -f "${tag}"
        git push
        git push -f --tags
        release=$(gh release create "${tag}" ${tag}.* --title "${tag}" --notes "${{ inputs.notes }}" | sed 's#/tag/#/download/#')

        # Copy the release .tgz for indexing
        mkdir -p /tmp/charts
        mv ${tag}.tgz /tmp/charts

        # Get the existing index.yaml for merging
        git show gh-pages:index.yaml > /tmp/index.yaml

        # Index the new release into the index.yaml
        helm repo index /tmp/charts --merge /tmp/index.yaml --url "${release}"

        # Save the new index.yaml
        mv /tmp/charts/index.yaml /tmp

        # Cleanup any working files and switch to the gh-pages branch
        git reset --hard
        git checkout gh-pages

        # Put the new index.yaml in place and commit/push it
        mv /tmp/index.yaml index.yaml
        git add index.yaml
        git commit -m "Generate Charts ${tag}"
        git push
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
